name = "wood"
main = "dist/server/index.js"
compatibility_date = "2026-05-11"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist/client"
binding = "ASSETS"

[vars]
PUBLIC_STORE_DOMAIN = "wood-123252.myshopify.com"
PUBLIC_STOREFRONT_API_TOKEN = "63ffd4fea36dc5a1d84b1b7b868518c2"
PUBLIC_CHECKOUT_DOMAIN = "wood-123252.myshopify.com"
PUBLIC_CUSTOMER_ACCOUNT_API_CLIENT_ID = "fdc3b180-af47-4cdb-82e0-d8afc05b5ff2"
PUBLIC_CUSTOMER_ACCOUNT_API_URL = "https://shopify.com/authentication/102713426262"
SHOP_ID = "102713426262"
GOOGLE_SHEET_ID = "1-pfqOs5DDdEWxQU87CFN3owluiIgpoZQ37jJYHcPQGg"

